# Environment
DEFAULT_SEED = 4
DEFAULT_MAZE_SIZE = 25
DEFAULT_CELL_SIZE = 2

WALKER = 4
BLOCKER = 3
STATIC = 2
TARGET = 1
EMPTY = 0

WALKER_POSITION = [1, 1]
BLOCKER_POSITION = [DEFAULT_MAZE_SIZE - 2, 1]
TARGET_POSITION = [DEFAULT_MAZE_SIZE - 2, DEFAULT_MAZE_SIZE - 2]

WALKER_LABEL_DICT = {
    WALKER: 'w',
    BLOCKER: 'i',
    STATIC: '#',
    TARGET: 't',
    EMPTY: ' '
}

WINDOW_TITLE = 'Dynamic walker'
SCENE_CELL_SIZE = 20
SCENE_BACKGROUND = 'white'
SCENE_COLORS_DICT = {
    WALKER: 'green',
    BLOCKER: 'red',
    STATIC: 'gray',
    TARGET: 'blue',
    EMPTY: 'white',
}

# Learning
EPISODES_COUNT = 10000
STEPS_COUNT = 500
EPSILON = 0.01
EPSILON_DECAY = 0.99
DISCOUNT_RATE = 0.95
LEARNING_RATE = 0.001
EXPLORATION_RATE = 1.0
AGENT_MEMORY_SIZE = 2048
BATCH_SIZE = 32
EPOCHS = 1
VERBOSE = 0

# Dependent variables (Don't change)
STATE_SIZE = DEFAULT_MAZE_SIZE * DEFAULT_MAZE_SIZE
SCENE_WIDTH = SCENE_CELL_SIZE * DEFAULT_MAZE_SIZE
SCENE_HEIGHT = SCENE_CELL_SIZE * DEFAULT_MAZE_SIZE
