# Environment
DEFAULT_SEED = 4
DEFAULT_MAZE_SIZE = 25
DEFAULT_CELL_SIZE = 2

WALKER = 4
INTERRUPTER = 3
STATIC = 2
TARGET = 1
EMPTY = 0

WALKER_LABEL_DICT = {
    WALKER: 'w',
    INTERRUPTER: 'i',
    STATIC: '#',
    TARGET: 't',
    EMPTY: ' '
}

WINDOW_TITLE = 'Dynamic walker'
SCENE_CELL_SIZE = 20
SCENE_WIDTH = SCENE_CELL_SIZE * DEFAULT_MAZE_SIZE
SCENE_HEIGHT = SCENE_CELL_SIZE * DEFAULT_MAZE_SIZE
SCENE_BACKGROUND = 'white'
SCENE_COLORS_DICT = {
    WALKER: 'green',
    INTERRUPTER: 'red',
    STATIC: 'gray',
    TARGET: 'blue',
}
